### ISSUE TITLE
Pushplugin using phonegap build 3.1.0 doesn't show the app title on notificacion (android)

### ISSUE THREAD

**Issue by ghost** [phonegap-build/PushPlugin#101]
I'm using pushplugin in my app, and until this moment without any problem, but when I updated it to phonegap 3.1.0 (using phonegap build) when a notification if recieved only the message is show (no the app tittle as before). No problem using ios

Anyone with the same problem?

Tested on android 4.2.2 (HTC One)
Using the same code - pgb 3.1.0

Example pictures here
http://community.phonegap.com/nitobi/topics/pushplugin_using_phonegap_build_3_1_0_doesnt_show_the_app_title_on_notificacion_android

**Comment by webbpage** [comment]
Oh man...I wish that I found this hours ago! This fixed all of my problems.
