### ISSUE TITLE
CDVPlugin class PushPlugin (pluginName: PushPlugin) does not exist

### ISSUE THREAD

**Issue by rhomeister** [phonegap-build/PushPlugin#117]
Hi,
I am trying to use PushPlugin on a PhoneGap (Cordova 3.1) App for iOS, testing with a iOS 7.0.4 device. However, when starting the app it reports the following error, and fails to call the registration method. 

```
2013-11-21 12:07:47.160 Brandweer Rooster[1804:60b] CDVPlugin class PushPlugin (pluginName: PushPlugin) does not exist.
2013-11-21 12:07:47.161 Brandweer Rooster[1804:60b] ERROR: Plugin 'PushPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2013-11-21 12:07:47.162 Brandweer Rooster[1804:60b] -[CDVCommandQueue executePending] [Line 117] FAILED pluginJSON = [
  "PushPlugin123143331",
  "PushPlugin",
  "register",
  [
    {
      "alert" : "true",
      "ecb" : "pushNotifications.IOSPushNotificationManager.onNotificationAPN",
      "sound" : "true",
      "badge" : "true"
    }
  ]
]
```

In Xcode I can see the 4 files in the plugins folder: PushPlugin.h and .m and AppDelegate+notification.h and .m

In the config.xml file I can see:

```
    <feature name="PushPlugin">
        <param name="ios-package" value="PushPlugin" />
    </feature>
```

The command for installing the plugin was:

```
phonegap local plugin add https://github.com/phonegap-build/PushPlugin
```

After this I did:

```
phonegap build ios
```

Other plugins (like the Splash Screen) work as expected. Also, the push notifications work for Android.

**Comment by mayurloved** [comment]
I my case After install Paypal Plugin I am facing issue.

I resolved its by add "PayPalMobileCordovaPlugin.m" in the Compile Source.

So you just need to add .m file in Compile source.

Add it works for me.

**Comment by Nitingadhiya** [comment]
I am also solve this problem.
1)  I am include file to plugin folder PushPlugin.h and .m , AppDelegate+notification.h and .m 
so solve this problem. 
If any one error . i will help you
