### ISSUE TITLE
ERROR:CLASS NOT FOUND

### ISSUE THREAD

**Issue by javapenguin** [phonegap-build/PushPlugin#119]
I copied the Example index.html file into my project.
(I am using cordova.js not phonegap.js)

When I run the application I get the following result:
- CORDOVA PUSHNITIFICATION PLUGIN DEMO
- DEVICEREADY EVENT RECEIVED
- REGISTERED ANDROID
- ERROR: CLASS NOT FOUND

I did add the following line to config.xml:

```
<plugin name="PushPlugin" value="com.plugin.gcm.PushPlugin" />
```

And all these classes are in src:

com.plugin.gcm.CordovaGCMBroadcastReceiver
com.plugin.gcm.GCMIntentService
com.plugin.gcm.PushHandlerActivity
com.plugin.gcm.PushPlugin

**Comment by pro-rakesh** [comment]
### This worked for me

> 1. install the ***_pushNotification plugin**_\* by runing following command:<br>
>    cordova plugin add https://github.com/phonegap-build/PushPlugin.git
> 2. Go to : <br>
>              project root folder > plugins > com.phonegap.plugins.PushPlugin > www ><br>
>              _Copy *_**PushNotification.js**\* file and paste it on 
>    _**project_root_folder > www > js**_
> 3. rebuid your app and run
