### ISSUE TITLE
onNotificationAPN and onNotificationGCM not called with cordova 3.4.0

### ISSUE THREAD

**Issue by lucasmilin** [phonegap-build/PushPlugin#176]
Hi everybody,

I'm using PushPlugin and I have a problem with onNotification callback. Both don't work. Do you have any solution to fix it fastly ?

pushNotification.register(
        successHandler,
        errorHandler, {
        "senderID":"12345678",
        "ecb":"onNotificationGCM"
    }
);

**Comment by appugouda** [comment]
Thanks judis . your solution worked for me ...cheers!!!
Hi All, I faced the same problem " onNotificationGCM not defined". I tried the solution suggested by Judis, and it worked for me without any problem.
Solution:
Instead of 
function onNotificationGCM(e) {
use
onNotificationGCM = function (e) {

**Comment by purinagripal** [comment]
Judis, your solution works for me! thank you

**Comment by kmraditya** [comment]
Sorry for the late response, Might be helpful for another developer like me.
Fixed the issue by simply changed the network connection and its start working.(with the same lines of code)
