### ISSUE TITLE
NSInternalInconsistencyException when calling register method

### ISSUE THREAD

**Issue by mrzmyr** [phonegap-build/PushPlugin#263]
Using [ionic](ionicframework.com), [parse sdk](https://parse.com/docs/push_guide#top/JavaScript) and cordova I having the following problem:

If I call the register method an exception will be thrown: 

**Code**

``` javascript
window.plugins.pushNotification.register(
    function () {}, 
    function () {}, 
    {"badge":"true","sound":"true","alert":"true", "ecb": "onNotificationAPN"}
)
```

**Exception**

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You have to call setApplicationId:clientKey: on Parse to configure Parse.'
...
libc++abi.dylib: terminating with uncaught exception of type NSException
```

A call with all notification options (badge, sound and alert) set to `false` xcode logs:

```
PushPlugin.register: Push notification type is set to none
THREAD WARNING: ['PushPlugin'] took '10.592285' ms. Plugin should use a background thread.
```

**Comment by ZouZou** [comment]
Hi there, I am trying to register my device in order for it to show in the Parse dashboard. however, I cannot seem to find a way, I know this question may seem very dumb but can you help out?
