### ISSUE TITLE
IOS push notification is not displayed in Adhoc but working fine in development.

### ISSUE THREAD

**Issue by joshilomas** [phonegap-build/PushPlugin#269]
Hello All,
I have successfully register the ios device for push notification and i had store it into my database for later use.
I have sent notification to ios device successfully while i have installed development version of my app. but As i generate .ipa file for Adhoc and distribute it to my friends. I am not getting any notifications..

**Comment by aslam23** [comment]
hello all
I have sent notification to ios device successfully while i have installed development version of my app.but when i installed app from ipa ad-hoc then device token is different and push
notification not working.
