### ISSUE TITLE
WAKE_LOCK required?

### ISSUE THREAD

**Issue by jnorris441** [phonegap-build/PushPlugin#294]
Users are complaining our app is keeping their phones awake, because the PushPlugin requires a WAKE_LOCK permission. 

Is it true that on Phonegap, push notifications do not work without having a full wakelock? Every app that uses this plugin prevents the phone from sleeping? Thanks

**Comment by hereiam133** [comment]
So this is the only Cordova plugin that I am using which has the WAKE_LOCK permission. My app will not go to sleep ever, is this a known issue with this PushPlugin?

**Comment by oliversalzburg** [comment]
@hereiam133 Just because it _can_ acquire a wake lock, doesn't mean it will constantly hold one.

**Comment by hereiam133** [comment]
@oliversalzburg So what has to happen to allow the app to sleep, nothing else uses wake lock and the app never sleeps.

**Comment by oliversalzburg** [comment]
@hereiam133 You should check the logs with logcat to see if wake locks are acquired and never released. There are other factors that can prevent your application from being stopping, like persistent connections.

**Comment by hereiam133** [comment]
@oliversalzburg Ah thanks for your help, that pointed out the cause, something with Camera-JNI and CameraFramework fire endlessly once the app opens. Moving in that direction.

**Comment by oliversalzburg** [comment]
@hereiam133 I'm glad I could help :) Cheers
