### ISSUE TITLE
Multiple notifications not working on Android

### ISSUE THREAD

**Issue by oliversalzburg** [phonegap-build/PushPlugin#298]
Whenever I receive a push notification on Android it replaces any existing notification in the drawer.

I saw https://github.com/phonegap-build/PushPlugin/issues/110 and https://github.com/phonegap-build/PushPlugin/pull/116, which suggest that this has been fixed but it's not working for me.

**Comment by ameeduddin** [comment]
I also have a problem,although I have resolved the problem where i have done some modifications so that I am now receiving the data corresponding to the notification touched from the tray from multiple notifications.The problem is when two  of the notification is touched all other notifications vanish.Could anyone suggest a remedy

**Comment by yytt** [comment]
as coolgastjen mentioned, it is fixed already by phonegap build.

**Comment by ameeduddin** [comment]
could you please share the java file where the code has been changed.

**Comment by williamazevedodepaula** [comment]
I solved the problem of the vanishing notifications...


I have made an approach to solve this issue. Please take a look in:

https://github.com/williamazevedodepaula/PushPluginExt/blob/master/README.md

In this version, when there are many notifications, clicking on any of them will call the callback function for any of the pending notifications, with an interval of 300 milisseconds between them. The msgcnt on each notification will show the order the notification were received.

The solution is not very ellegant, but do the work!
I will like sugestions!!
Thanks!

**Comment by 05bca054** [comment]
Hello William,

Thanks for awesome piece of work but  this plugin available on phonegap build?

-Niks
