### ISSUE TITLE
Android: processMessage failed: Error: ReferenceError: onNotification is not defined

### ISSUE THREAD

**Issue by criticalhit052** [phonegap-build/PushPlugin#300]
I have been working with PushPlugin for a couple of days and have run into a peculiar error. Whenever I run the app for the first time and it registers the RegID with the GCM server, I get this:

"processMessage failed: Message: Jjavascript:onNotification({"regid":"regidhere","event":"registered"})"

along with the error within the title, the app then throws an alert for the success handler, not the error handler. Once that has occured, I attempt to send a push note using the "pushGCM.rb" file which returns 3 errors, all "processMessage failed:" and it contains the payload, the app then doesn't trigger the "e.foreground" statement and nothing happens. However, and this is where it gets weird. The app when running in the background, and when not running at all, will trigger a push notification. I have searched for days for a resolution to this issue to no avail. Anyone have any ideas?

**Comment by jieves** [comment]
I'm having the same problem : 
processMessage failed: Error: ReferenceError: onNotification is not defined
processMessage failed: Stack: ReferenceError: onNotification is not defined
    at eval (eval at processMessage (file:///android_asset/www/phonegap.js:1020:26), <anonymous>:1:1)
    at processMessage (file:///android_asset/www/phonegap.js:1020:13)
    at Function.androidExec.processMessages (file:///android_asset/www/phonegap.js:1090:13)
    at pollOnce (file:///android_asset/www/phonegap.js:955:17)
    at pollOnceFromOnlineEvent (file:///android_asset/www/phonegap.js:945:5)

Can anyone help me ?

**Comment by criticalhit052** [comment]
For me specifically it had something to do with how the "onNotification" script was being called, try and make sure that main body of code is referencing the script properly and that also it's being called in the right order, other than that I don't know what your problem is, this is  what solved it for me

**Comment by jorge-cp** [comment]
When we had this issue, the my problem turned out to be the scope of onNotification. Make sure it is available at the time you call it.
