### ISSUE TITLE
[Android] Tapping a notification does not bring application from background to foreground

### ISSUE THREAD

**Issue by piyushhari** [phonegap-build/PushPlugin#35]
On Android, if application is running in background and a notification arrives, the notification is queued in Notification drawer. When a user taps the notification, the application does not come in foreground although the event callback for receiving notification is called.

**Comment by Asit1989** [comment]
I am facing the same issue. Nothing happens when I tap on push notification. Anybody found any solution?

**Comment by khushbooTriend** [comment]
use this.. it works for me..  
 notifyIntent.setAction(Intent.ACTION_MAIN);
        notifyIntent.addCategory(Intent.CATEGORY_LAUNCHER);

**Comment by jahertor** [comment]
The opened activity shouldn't be singleInstance. As singleTop and singleTask the activity is opening correctly.

**Comment by diegobill** [comment]
Same problem here using phonegap-push-plugin on device (Moto X 2G): 

```
$ ionic info

Your system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v7.6.0
Xcode version: Not installed


$  cordova plugin version | grep phonegap-plugin-push
phonegap-plugin-push 1.9.4 "PushPlugin"


$ cordova platform version android
Installed platforms:
  android 6.1.2
  browser 4.1.0
  ios 4.3.1
Available platforms: 
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  ubuntu ~4.3.4
  webos ~3.7.0
```

**Comment by diegobill** [comment]
Now It is works, I have to insert cordova.plugins.backgroundMode.moveToForeground(); from https://github.com/katzer/cordova-plugin-background-mode in my on('notification')

**Comment by krishnanv001** [comment]
@diegobill i am using cordova-plugin-fcm its works well.While app running background device receive notification but user tab that notification cannot call specific page content its shows device ready to open app normally.any solution for this problem.

**Comment by diegobill** [comment]
@krishnanv001 , thanks if I can not do with phonegap-plugin-push I will change the lib to cordova-plugin-fcm
