### ISSUE TITLE
WP8 event.uri empty

### ISSUE THREAD

**Issue by gustter** [phonegap-build/PushPlugin#394]
Hi there.

I'm trying to send push notifications in WP8 , but in channelHandler (event) I get event.uri empty!

My code:

pushNotification.register(
				        channelHandler,
				        pushNotificationErrorHandler,
				        {
				            "channelName": windowsChannelName,
				            "ecb": "onNotificationWP8",
				            "uccb": "channelHandler",
				            "errcb": "jsonErrorHandler"
				        });

function channelHandler(event) {
	alert(event.uri);  ---->>>>>> EMPTY!!!
}

Any suggestions ?

Thanks!

**Comment by MingxuanLi** [comment]
Anyone has fixed this ? I am getting the same problem all the time

**Comment by gustter** [comment]
Yes, you have to ask for the uri several times. yes, so strange, but Microsoft is Microsoft :)

**Comment by MingxuanLi** [comment]
@gustter 
Yes, place an interval in your code to fetch uri should work.

**Comment by ericci** [comment]
How many times? I tested with 50 and didn't work. :-(

**Comment by rakatyal** [comment]
Make sure the date and time settings for your devices are correct before trying. There was a glitch in the first registration which has been fixed.
