### ISSUE TITLE
onNotificationGCM not called!

### ISSUE THREAD

**Issue by mariohmol** [phonegap-build/PushPlugin#395]
Hy,

I have a phonegap project with pushplugin installed as readme (i did it like 8 times).

It send the register with project ID but onNotification is not fired, so no token.

V/PushPlugin(871): execute: action=register
 V/PushPlugin(871): execute: data=[{"senderID":"1015195888033","ecb":"onNotificationGCM"}]
 V/PushPlugin(871): execute: jo={"senderID":"1015195888033","ecb":"onNotificationGCM"}
 V/PushPlugin(871): execute: ECB=onNotificationGCM senderID=1015195888033
 V/GCMRegistrar(871): Registering receiver
 resetting backoff for br.com.mobile
 Registering app br.com.mobile of senders 1015195888033
 THREAD WARNING: exec() call to PushPlugin.register blocked the main thread for 140ms. Plugin should use CordovaInterface.getThreadPool().

My Enviroment:
Ubuntu 64 - 3.11.0-26-generic #45~precise1-Ubuntu

Latest ADT and SDK 20140702

Java: java version "1.6.0_33"
OpenJDK Runtime Environment (IcedTea6 1.13.5) (6b33-1.13.5-1ubuntu0.12.04)
OpenJDK Server VM (build 23.25-b01, mixed mode)

Android 4.4.2
android-supportv13
cordova.js - var PLATFORM_VERSION_BUILD_LABEL = '3.6.4';
jquery-1.9.1.min.js

Tested using emulator and real mobile

Now I will do a pure android to test...

Any ideas?

**Comment by ghominejad** [comment]
@mariohmol : Have you found any solution ?

**Comment by mariohmol** [comment]
i had to reset the device to the factory..  after that worked
i guess that after installing the same app a lot of times (as i was developing) something was in cache in mobile.. 
so i think that , in real world, the user will install just once and then it will not occur in procution site

**Comment by ghominejad** [comment]
i hope
thank you
