### ISSUE TITLE
only getting string “OK” instead of the device/registration id from cordova push plugin using Android

### ISSUE THREAD

**Issue by mypark** [phonegap-build/PushPlugin#411]
I've set up the push notification plugin and am calling the register method, but it's only returning a string "OK" instead of a device id. How do I get the registered device id?

```
 $window.plugins.pushNotification.register(
      function (result) {
        q.resolve(result); //this always just returns the string "OK" and not the e.event, e.regid
      },
      function (error) {
        console.log(error);
        q.reject(error);
      },
      config);

    return q.promise;
  },
```

I took a look at logcat on android and see the intentservice is being fired

   V/GCMIntentService(24849): onRegistered: SOMELONGIDGOESHERE
   V/GCMIntentService(24849): onRegistered: {"regid":"SOMELONGIDGOESHERE,"event":"registered"}
   V/PushPlugin(24849): sendJavascript: javascript:angular.element(document.querySelector('[ng-app]')).inject

on iOS the register function returns a deviceID as a string, wheras in Android it's just the "OK" string.  Should I be handling the registration event only on an onNotification handler?

**Comment by Kaushick** [comment]
I'm getting the same response. Please help me to find the registration id fro android. Is there any other method or should I pass some extra parameter in config?

**Comment by mypark** [comment]
see here
http://stackoverflow.com/questions/27207588/only-getting-string-ok-instead-of-the-device-registration-id-from-cordova-push/27214510?noredirect=1#comment49072130_27214510
