### ISSUE TITLE
WP8 - Never entering in channelHandler 

### ISSUE THREAD

**Issue by sdmdev** [phonegap-build/PushPlugin#417]
I automatically installed the plugin with

cordova plugin add https://github.com/phonegap-build/PushPlugin.git
registered it when my device is ready

function registerMPNS() {
    console.log("registerMPNS");
    var pushNotification;
    pushNotification = window.plugins.pushNotification;
    pushNotification.register(
    channelHandler,
    errorHandler,
    {
        "channelName": "myChannelTm123",  
        "ecb": "onNotificationWP8",    
        "uccb": "channelHandler", 
        "errcb": "jsonErrorHandler"
    });
}
Waiting in channelHandler to get my URI which will then be passed to my server

function channelHandler(event) {
    console.log("channelHandler ...");
    var uri = event.uri;
    console.log("uri: " + uri);
}
//handle MPNS notifications for WP8 function onNotificationWP8(e) { ... }

function jsonErrorHandler(e) {
    ...
}
The problem is that I am never entering in channelHandler, Am I missing anything or misunderstood its usage?

**Comment by marcelotq** [comment]
I have the same problem. Can someone help us? Thanks

**Comment by rakatyal** [comment]
The docs have been updated. Kindly refer them for the solution.
