### ISSUE TITLE
on wp8 Channel.uri is empty

### ISSUE THREAD

**Issue by fredericks** [phonegap-build/PushPlugin#432]
Hi,.

I'm testing this plugin on a windows phone 8.1 and  when I call register I always get an empty uri.
Any idea?
Thanks

this is the code:

		var channelName = "XXXXXX";
		var pushNotification = window.plugins.pushNotification;
		console.log(pushNotification);

		try {
			var channelHandler = function(result){
				console.log(result);
				EMAPP.Channel = result;
				//alert(result);				
			};
			
			var channelUriHandler = function(result){
				console.log(result);
				EMAPP.Channel = result;
				//alert(result);				
			};			

			var errorHandler = function(error){
				alert(error);
			};		
		
			if (device.platform == "Win32NT")
			{
					pushNotification.register(channelHandler, errorHandler,
							{
									"channelName": channelName,
									//"ecb": "onNotificationWP8",
									"uccb": "channelUriHandler",
									"errcb": "jsonErrorHandler"
							});					
			}

**Comment by luca-zini** [comment]
I have the same issue on an application that was working correctly a few weeks ago.
I'm trying to get a valid uri since yesterday wihout succes

**Comment by fredericks** [comment]
Hi Luca, I am using a workaround. I simply retry to register the channel if channeluri is empty, until it gets something.
It usually gets a channel uri at the second try.

**Comment by ggiordan** [comment]
Anyone make any progress on this?
It looks like the PushChannel_ChannelUriUpdated is never called back?
I've isolated the code into it's own project and get the same result.
I also get the same result w/the sample code from microsoft.
The callback never seems to get called... it seems to have broken w/the 8.1 update? (I have a nokia 928 as a test device)

**Comment by JohnReeser** [comment]
I have the same problem! I even tried your code above. Every call to "register" is successful, and it calls back "channelHandler". But with empty URI. No matter how many times I call it. (I tried 500+ times).

The other interesting thing is that "register" is successful even if the phone is not connected to 4G or WiFi. I assume it needs to talk to Microsoft cloud before it give me the URI, but it does not look like it is talking to anyone. I took the SIM card out of the phone, disabled WiFi - still success (with empty URI). Even in airplane mode. 

Anyone got it to work?..

Thanks!

Nokia Lumia 521 Windows Phone 8.1
PushPlugin 2.4.0
PhoneGap 4.2.0-0.23.0
Visual Studio Express 2013 for Windows

**Comment by MingxuanLi** [comment]
I am getting the same thing, can anyone suggest a solution ?

**Comment by marcelotq** [comment]
Me too. Someone has a solution? Thanks

**Comment by MingxuanLi** [comment]
@marcelotq 

The simple solution is - $interval to fetch the uri until success then cancel the interval.

**Comment by marcelotq** [comment]
Thanks MingxuanLi but how I do this? Can you give me a example? Thanks

**Comment by MingxuanLi** [comment]
@marcelotq 

I am using angular js. Below is the pseudo code:

var fetch_uri = function(){
       // Fetch Uri code goes here
       
       // if uri found
       if(uri.length > 0){
            $interval.cancel(get_uri);
       }
};

var get_uri = $interval(fetch_uri, 500);

**Comment by marcelotq** [comment]
Ok MingxuanLi, thanks very much my friend.

Regards,
Marcelo

**Comment by rakatyal** [comment]
This issue has been fixed now.

**Comment by shinryuken0505** [comment]
Hi , I already try it out.One of solution is  Let all function parameters with "".
EX:
Wrong:
 "channelName": channelName,

Correct:
 "channelName": "channelName",

**Comment by ghost** [comment]
@shinryuken0505, your solution didn't work for me:

``` javascript
this.pushNotification.register(channelHandler, errorHandler, {
    "channelName": "MyPushChannel",
    "ecb": "onNotificationWP8",
    "uccb": "channelHandler",
    "errcb": "jsonErrorHandler"
});
```

**Comment by shinryuken0505** [comment]
@ricardovigatti  Here's my ok code...Just like yours.
 pushNotification.register(
        channelHandler,
        errorHandler,
        {
            "channelName": "WindowChannel",
            "ecb": "onNotificationWP8",
            "uccb": "channelHandler",
            "errcb": "jsonErrorHandler"
        });

Maybe problem is in another code !?

**Comment by ghost** [comment]
Yea, i think it's something related to MPNS service itself.
