### ISSUE TITLE
Amazon FireOS project will not compile / build fails with PushPlugin

### ISSUE THREAD

**Issue by exboreas** [phonegap-build/PushPlugin#444]
Using latest Cordova version 4.2.0 and amazon-fireos version 3.7.0-dev the default project will not compile if PushPlugin is added to the project. This happens with a brand new project as created by the "cordova create" command, without any modifications to the project. This seems to be a problem with PushPlugin and Amazon FireOS rather than my setup because I'm able to create projects for Amazon FireOS with other plugins but not PushPlugin. (I'm also able to create projects for Android with PushPlugin.)

To replicate error, simply use these commands:

cordova create [with appropriate parameters for new project]
cordova platform add amazon-fireos
cordova plugin add https://github.com/phonegap-build/PushPlugin.git
cordova build amazon-fireos

The output is:

BUILD FAILED
C:\adt-bundle-windows-x86_64\adt-bundle-windows\sdk\tools\ant\build.xml:720: The
 following error occurred while executing this line:
C:\adt-bundle-windows-x86_64\adt-bundle-windows\sdk\tools\ant\build.xml:734: Com
pile failed; see the compiler error output for details.

Total time: 2 seconds

[project-directory]\platforms\amazon-fireos\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s,/c,ant,debug,-f,[project-directory]\platforms\amazon-fireos\build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
ERROR building one of the platforms: Error: [project-directory]\platforms\amazon-fireos\cordova\build.bat: Command failed with exit code 8
You may not have the required environment or OS to build this project

**Comment by Sirlazer2** [comment]
Having same issue with Android.

I know my PATH, JAVA_HOME and ANT_HOME is working, so It's really a bothering problem.

**Comment by shazarn** [comment]
Hi guys,
DId you ever get a fix for this?
I have just run into the same issue using 4.2 and IOS

**Comment by exboreas** [comment]
I didn't find a fix but I haven't looked at this issue since I posted it. It will be a while before I look at it again because it's not urgent for me. I hope the issue is resolved in a future version of the plugin.

**Comment by clauderic** [comment]
Any update? I'm having the same issue

**Comment by exboreas** [comment]
Use https://github.com/phonegap/phonegap-plugin-push instead.
