### ISSUE TITLE
[ Android ] How to use custom icon image

### ISSUE THREAD

**Issue by banksector7** [phonegap-build/PushPlugin#452]
Dear All,

I see that when we receive notification, Title, message and the default icon of the app will be displayed.  However, if i want to display my own icon image (from image url or file) How can i do this for Android?

**Comment by ravindernegi85** [comment]
you need to replace. default icons with your icon. please see the link http://docs.phonegap.com/en/4.0.0/config_ref_images.md.html

**Comment by banksector7** [comment]
@ravindernegi85   I succeed with your suggestion. But it's not my requirement. If i have a following code on Server...

message.addData('title','User A');
message.addData('message','Hello');
message.addData('imageurl,'URL of image Here'); 

For example, User A send the message to User B and User B gets the notification. User B should see the profile picture of User A (based on User A's picture url) at the notification instead of the icon. This is what i want.

Can this plugin technically do this?

**Comment by ghominejad** [comment]
@banksector7 have you found any solution?

**Comment by banksector7** [comment]
@ghominejad   I already found the solutions. From the backend, i send the URL of the image to the app and using GCMIntentService.java to convert image from URL to bitmap.

**Comment by ghominejad** [comment]
I'm not java programmer is it possible explain it a little more, how you convert the url to bitmap using GCMIntentService.java?

**Comment by ghominejad** [comment]
Do i need an external library to convert a url to icon?

**Comment by banksector7** [comment]
@ghominejad  The working source code is at my office. I'll reply you with the sample code when i'm at there. We'll use setLargeIcon for this!  Please wait!

**Comment by ghominejad** [comment]
Thank you
