### ISSUE TITLE
custom sound while app running background - iOs

### ISSUE THREAD

**Issue by serhanbuy** [phonegap-build/PushPlugin#457]
Hi guys,
first of all thank you for the wonderful plugin, and documentation. 
I wanted to inform other users about a problem I had using this plugin.

If you want to play a **custom sound** for the notification while app is closed or running in background for iOs, you have to manually put inside the Resources folder in xCode. Otherwise it will play the default sound.
![screen shot 2015-01-17 at 06 27 07](https://cloud.githubusercontent.com/assets/2011206/5787684/f240b7c0-9e11-11e4-8ce7-84c2af8d5af1.png)

**Comment by andreapozzetti** [comment]
What about the path to play a custom sound?

**Comment by serhanbuy** [comment]
The file should be directly in www (for iOs, in Android it is different), but this only applies if you want to play the sound while the app is in foreground. 

For the custom sound to play while the app is in background, you have to drag the file to your xcodes Resources folder. see the screenshot in the first post.

**Comment by lihlio** [comment]
hi @serhanbuy why my app not play default sound in ios ?
