### ISSUE TITLE
Getting a java error in javascript... java.lang.Long cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by marie-dk** [phonegap-build/PushPlugin#476]
I installed the plugin a few days ago, but the errorHandler is not able to log to console, because of this error:  java.lang.Long cannot be cast to java.lang.String. Any idea why?

pushNotification = window.plugins.pushNotification;   

  function register() {
    pushNotification.register( 
      successHandler, 
      errorHandler, 
      { 'senderID':'some_id_here', 'ecb':'onNotificationGCM'} 
    );
  } 

  function successHandler(result) { 
    console.log('Success: '+ result); 
  }

  function errorHandler(error) { 
    //** The following line throws: 
    //** java.lang.Long cannot be cast to java.lang.String
    console.log('Error:' + error);
  }

Samsung Galaxy S5
Android 4.4.2
Chrome 30.0 (in webview)
Cordova 3.6.3-0.2.13

**Comment by ghominejad** [comment]
marie-dk: Have you found any solution ?

**Comment by marie-dk** [comment]
Yes... sorry.... i did find a solution. I have an object containing configuration, and in there I had the senderID as a number instead of a string. I just need to add quotes around the id so that it is passed as a string :-)
