### ISSUE TITLE
WP8 push notification issue - An unknown error has occurred. Error: 80020101

### ISSUE THREAD

**Issue by MingxuanLi** [phonegap-build/PushPlugin#500]
Hi,

I am trying to get the push plugin working in wp8. Paste my code below:

var winConfig = {
         "channelName" : "test",
         "ecb" : "onNotificationWP8",
         "uccb" : "channelHandler",
         "errcb" : "jsonErrorHandler"
};
pushNotification.register(wpSuccessHandler, wpErrorHandler, winConfig);

But I always am getting an empty uri in the data from the callback wpSuccessHandler.

With the following exception:

A first chance exception of type 'System.SystemException' occurred in Microsoft.Phone.Interop.ni.dll
ERROR: Exception in InvokeScriptCallback :: An unknown error has occurred. Error: 80020101.

Can anyone advise/help with this ?

**Comment by MingxuanLi** [comment]
Just tried a couple of times, sometimes return empty uri, sometimes return the valid uri.

Not sure what's wrong here

**Comment by fabiofapeli** [comment]
I have the same problem, are you fix the problem?

**Comment by MingxuanLi** [comment]
I did, trying using $interval until you got the uri.

**Comment by fabiofapeli** [comment]
Funcionou uma versão quando publiquei na WP loja na segunda tentativa, porém alguma atualização que fiz deixou de funcionar. Você pode enviar o seu código, pois algum detalhe deve estar fazendo a diferença.

**Comment by fabiofapeli** [comment]
It worked when I published a version in WP store on the second try, but I did some updating crashed. You can send your code because some detail should be making a difference.

**Comment by qiqbal** [comment]
It always works for me for the second time. First time is always empty, simply ignore it and try one more time.

**Comment by MingxuanLi** [comment]
Very interesting this repo/plugin looks like no longer being supported !!! Everyone trying to use a walk around to solve this problem !

**Comment by rakatyal** [comment]
Make sure the date and time settings are correct on your device and then try. This issue has been addressed.
