### ISSUE TITLE
WP8 notification

### ISSUE THREAD

**Issue by vespino** [phonegap-build/PushPlugin#517]
I'm using the following code:

	//pushNotification
	try 
	{
		pushNotification = window.plugins.pushNotification;
		
		switch(device.platform) {
			case 'Android':
				pushNotification.register(successHandler, errorHandler, {
					"senderID":"1234567890",
					"ecb":"onNotification"
				});
				break;

			case 'Win32NT':
				pushNotification.register(register_token, errorHandler, {
					"channelName": "channelName",
					"ecb": "onNotificationWP8",
					"uccb": "register_token",
					"errcb": function(error) {
						navigator.notification.alert(error.message, nothing, 'Title', 'Sluiten');
					}
				});
				break;

			default:
				pushNotification.register(register_token, errorHandler, {
					"badge":"true",
					"sound":"true",
					"alert":"true",
					"ecb":"onNotificationAPN"
				});
		}
	}
	catch(err)
	{
		errorHandler(err.message);
	}

Will this work? And what is needed to send WP8 push notifications? I have managed to get it to work on Android and iOS but WP isn't quite that clear to me. I'm saving tokens to a server for later purposes, I guess I have to do the same with the url returned with "register_token"? The url is WP's version of the token that Android and iOS use right?

Help :s

**Comment by qiqbal** [comment]
Yes

**Comment by vespino** [comment]
That simple eh?

**Comment by rakatyal** [comment]
Yes. You would use the uri to send push notifications through your cloud service. 
https://msdn.microsoft.com/en-us/library/windows/apps/hh202967(v=vs.105).aspx
