### ISSUE TITLE
The example does not work.

### ISSUE THREAD

**Issue by SMJ93** [phonegap-build/PushPlugin#529]
Hi,

I have downloaded the example zip and opened it in Xcode. It outputs the following error when I run it on my iPhone 5S.

`2015-04-17 16:29:19.754 NotificationExample[4807:1649932] CDVPlugin class CDVDevice (pluginName: Device) does not exist.
2015-04-17 16:29:19.754 NotificationExample[4807:1649932] ERROR: Plugin 'Device' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2015-04-17 16:29:19.754 NotificationExample[4807:1649932] -[CDVCommandQueue executePending] [Line 159] FAILED pluginJSON = ["Device1988003203","Device","getDeviceInfo",[]]`

Cheers, Stu

**Comment by arieljake** [comment]
did you install the Device plugin:

````cordova plugin add org.apache.cordova.device````

**Comment by SMJ93** [comment]
It says its already installed.. and when I run "Cordova platform ls" it is listed there.

**Comment by SMJ93** [comment]
When I run "cordova save plugins --experimental" it says "Skipping org.apache.cordova.device, not a top-level plugin". 

This comment updates the XML with all the installed plugins.

**Comment by SMJ93** [comment]
I got it working!

I created an empty project from scratch using the Cordova command line interface and installed the plugin's my self. I then copied the html / css / javascript across and it worked fine. I guess there is a problem with how the plugins have been installed with the example kitchen sink app.

Great plugin though!

Cheers, Stu
