### ISSUE TITLE
conflict with Local notofication

### ISSUE THREAD

**Issue by volodymyrl** [phonegap-build/PushPlugin#570]
I added push notification to my App but it conflicts with Local Notification plugin - when I lock a screen or get a new push notification it clears all my local notifications. Some one know why it happens? Thanks!

**Comment by DevRecords** [comment]
I have exactly the same issue. All notifications gets deleted after a while.

**Comment by vlysytsia** [comment]
This is a solution - just add  "clearNotifications": false to push notification init

```
    var push = PushNotification.init({
            "android": {
            "senderID": "114273210157",
            "clearNotifications": false
           },
           "ios": {"alert": "true", "badge": "true", "sound": "true"}
          });
```
