### ISSUE TITLE
Cordova android build error: incompatibility with another plugin

### ISSUE THREAD

**Issue by braianj** [phonegap-build/PushPlugin#573]
After trying and trying, I found that the error that i'm having is an incompatibility between cordova facebook plugin and push plugin. 
If one of those is installed separately, cordova build android works, but if I install both, the error appears:

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:preDexDebug
:dexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/.../Android SDK/adt-bundle-mac-x86_64-20140702/sdk/build-tools/22.0.1/dx --dex --no-optimize --output /.../platforms/android/build/intermediates/dex/debug --input-list=/.../platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

So now I found the problem, but I don't have the answer.

> Cordova 5.0.0
> Android 4.0.0

> Plugins
> com.phonegap.plugins.PushPlugin 2.4.0 "PushPlugin"
> com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"
> com.telerik.stripe 1.0.4 "Stripe"
> org.apache.cordova.device 0.3.0 "Device"
> org.apache.cordova.dialogs 0.3.0 "Notification"
> org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
> org.apache.cordova.network-information 0.2.15 "Network Information"
> org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
> org.apache.cordova.vibration 0.3.13 "Vibration"

**Comment by kaansoral** [comment]
Just google or search the issue man, there are more than 20 issues that reference this specific problem

The easiest solution is to use the Telerik versions of both plugins, which are ahead in development and maintained by EddyVerburgen

**Comment by braianj** [comment]
Yeah well, thanks for the "Just google", never came to my mind :worried:  
if I post this here, it's because none of the answers I found on the search works. And I think that's why it's time to update these plugins.

**Comment by kaansoral** [comment]
I posted my solution to maybe 10 issues as an unrefuted solution, it works

The plugins are updated at Eddy's forks

I agree that these plugins need to be updated regularly, both of the plugins are the most major and most mis-owned plugins of cordova, so better use Eddy's plugins/forks whenever you can

There is also a new push plugin, but I haven't tested it yet

**Comment by braianj** [comment]
Have you any links?
This "solutions" make me for sure, put hand on code, when I just want to build como UI fix of my already working android app. So it's so frustrating that every time that I need to fix a thing in the code, spend hours to fix a thing of the plugins.

**Comment by kaansoral** [comment]
You claim you google, yet you are still asking for links :), anyway, here they are:
https://github.com/Telerik-Verified-Plugins/PushNotification
https://github.com/Telerik-Verified-Plugins/Facebook

**Comment by braianj** [comment]
Again, this is to try to fix issues and post solutions, so what is the sense of post solutions like Use Google. And if solutions were not written the god 'google' (Praise) would not be working at all.
Thanks anyway.

**Comment by braianj** [comment]
@kaansoral the PushNotificacion is requiring to register to the Telerik Platform, but is that paid? is the only way?

**Comment by kaansoral** [comment]
I don't think that is the case, I'm using the plugin without issues on Android and iOS

For me it's no different than this plugin

**Comment by braianj** [comment]
ok, thanks. I just fixed the old push plugin, just 1 line and 1 file. Thanks man

**Comment by braianj** [comment]
So I'll publish here my solution.

After install by cordova cli, went to plugins/com.phonegap.plugins.PushPlugin/plugin.xlm

On line 66 change 
```
<source-file src="src/android/com/plugin/android-support-v13.jar" target-dir="libs/"/>
```
for
``` 
<source-file src="src/android/com/plugin/android-support-v4.jar" target-dir="libs/"/>
```

then on plugins/com.phonegap.plugins.PushPlugin/src/android/com/plugin/ replace the files as we do on the replaced line.


> cordova platform rm android
> cordova platform add android
> cordova build android
