### ISSUE TITLE
After installing the plugin getting UNEXPECTED TOP-LEVEL EXCEPTION when building for android

### ISSUE THREAD

**Issue by softBarbarian** [phonegap-build/PushPlugin#583]
After installing the plugin getting UNEXPECTED TOP-LEVEL EXCEPTION when building for android
```
 UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
```

If i remove the plugin and remove and readd android platform not installing the plugin this time - apk compiles fine.

here is my info:
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
barbarian:Trax barbarian$ ionic info

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.8
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: 1.6.2 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.2 Build version 6D2105 

```

**Comment by christocracy** [comment]
- This plugin has [313 open issues](https://github.com/phonegap-build/PushPlugin/issues)
- Last commit [October 3](https://github.com/phonegap-build/PushPlugin/commits/master).

This plugin is dead.

**Comment by christocracy** [comment]
If you want awesome push services, talk to Brian at http://cloudfiveapp.com and use his [Push Cordova Plugin](https://github.com/cloudfive/push-cordova-plugin)

**Comment by softBarbarian** [comment]
agreed, we are going with https://www.cloudfiveapp.com

**Comment by softBarbarian** [comment]
you beat me to it... :)

**Comment by christocracy** [comment]
I have an outstanding PR on his Push Plugin.  https://github.com/cloudfive/push-cordova-plugin/pull/3

**Comment by ekonstantinidis** [comment]
Is there any progress with this issue? Got the same problem and the only way to build successfully for android is to remove *Push Plugin*.

**Comment by christocracy** [comment]
You will get no response from the plugin authors here.  They have left the building.

**Comment by ekonstantinidis** [comment]
I've managed to make it build successfully by following [this PR](https://github.com/phonegap-build/PushPlugin/pull/588/files).

Make sure that you remove the platform first, then do the changes and the re-add the platform. Then it builds successfully!
