### ISSUE TITLE
CDVPlugin class PushPlugin (pluginName: PushPlugin) does not exist.

### ISSUE THREAD

**Issue by Ziv-Barber** [phonegap-build/PushPlugin#593]
When I tried to use 'register' in iOS:

CDVPlugin class PushPlugin (pluginName: PushPlugin) does not exist.
ERROR: Plugin 'PushPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
[CDVCommandQueue executePending] [Line 159] FAILED pluginJSON = ["PushPlugin1238288124","PushPlugin","register",[{"alert":"true","ecb":"mainApp.onNotificationAPN","sound":"true","badge":"true"}]]

**Comment by ericraio** [comment]
:+1:
