### ISSUE TITLE
Android icon background color

### ISSUE THREAD

**Issue by barryvdh** [phonegap-build/PushPlugin#619]
In Android, it's possible for the icon to set the background value. Perhaps this could be a configuration option?

```java
NotificationCompat.Builder mBuilder =
			new NotificationCompat.Builder(context)
				.setDefaults(defaults)
				.setSmallIcon(smallIcon)
				.setColor(0xFF123456)
```

**Comment by macdonst** [comment]
@barryvdh if you look at the new push plugin documentation you can see we've fixed this issue:

https://github.com/phonegap/phonegap-plugin-push/blob/master/README.md#images

**Comment by barryvdh** [comment]
Yeah I switched to that. So why isn't there a message about this being deprecated or something?
