### ISSUE TITLE
Blackberry 10 not calling success or error handler on register

### ISSUE THREAD

**Issue by mikes000** [phonegap-build/PushPlugin#632]
Hello,

I am having an issue where blackberry 10 does not seem to call either the success or error handler when calling register on the push notification plugin.

Is there a case when neither the success or error would not get called? I cannot get our devices to receive notifications.

Here is a snippet of the code

```

function errorHandler(error) {
	//never calls the error handler
}
function successHandlerBB(result) {
    //never calls the successhandler
       ...
}
// BlackBerry10
function onNotificationBB(pushpayload) {
             //never gets here
             ...
}

pushInstance = window.plugins.pushNotification;
addCallback('notificationHandler', onNotificationBB);
pushInstance.register(
    successHandlerBB,
    errorHandler,
    {
        invokeTargetId : "com.ourid.invoke.push",
        appId: ".......", 
                ppgUrl:"http://cpxxxx.pushapi.eval.blackberry.com",
        ecb: onNotificationBB,
        simChangeCallback: simChangeCallback,
        pushTransportReadyCallback: onPushTransportReady,
        launchApplicationOnPush: true
        }
);
```

Thanks!

**Comment by chetanporiya** [comment]
Hi mikes,
i have implemented same using below code snippet please try this,
i have registered my device on launching of my application please make sure your device is connecting with internet.

function successHandler(result) {
    alert(JSON.stringify(result));
}
function errorHandler(error) {
    alert(JSON.stringify(error));
}

 var app = {
        initialize: function() {
            this.bindEvents();
        },
        bindEvents: function() {
            document.addEventListener('deviceready', this.onDeviceReady, false);
        },
        onDeviceReady: function() {
            try {
                pushNotification = window.plugins.pushNotification;  
                var options = {
                        invokeTargetId: "com.ourid.invoke.push",
                        appId: "........",
                        ppgUrl: "http://cpXXXX.pushapi.eval.blackberry.com",
                        ecb: "pushNotificationHandler",
                        launchApplicationOnPush: true
                    };
                    pushNotification.register(successHandler, errorHandler, options);  
            } catch (err) {
                console.log(err);
            }
    }
};  
app.initialize();

**Comment by mikes000** [comment]
Thanks chetanporiya,

I have tried the code in another app and everything is functioning correctly but not in this one particular app. I think it has something to do with the specific setup of the app. I am going mark this item as closed since I am not able to replicate it in another app.

**Comment by chetanporiya** [comment]
Ok Great.
