### ISSUE TITLE
Question: Why was this plugin deprecated?

### ISSUE THREAD

**Issue by emgeee** [phonegap-build/PushPlugin#638]

**Comment by macdonst** [comment]
Mostly because the API was a mess. Instead of forcing everyone to change their code I wrote a new plugin that has a more consistent API. Development on this plugin has stopped but it will remain around for those who do not want to move to the new plugin.

**Comment by billp72** [comment]
How do I integrate the new plugin into my angularjs app? Before, I saw, you could just include <script type="text/javascript" src="PushNotification.js"></script> Can I still do this? I have a service that doesn't seem to play nice with the new plugin. Thanks

**Comment by billp72** [comment]
<code><script type="text/javascript" src="PushNotification.js"></script></code>

**Comment by billp72** [comment]
include PushNotification.js into index.html
