### ISSUE TITLE
Push Plugin register failed - iOS

### ISSUE THREAD

**Issue by karthikeyan-perpetua** [phonegap-build/PushPlugin#650]
I'm new to app development. I have received following error while registering iOS device ,

Error:
PushPlugin.register: setting badge to false
PushPlugin.register: clear badge is set to 0
Push Plugin register failed

Thanks in advance

**Comment by muvaf** [comment]
Try adding iOS Development provisioning file, not distribution. it worked for me.

**Comment by karthikeyan-perpetua** [comment]
@muvaffak 

Thanks for your response. Its works :+1:

**Comment by sirhodes** [comment]
Also got this issue and same exact message after upgrading to Xcode 8 and iOS 10, for whatever reason the "Push Notifications" switch in the "Capabilities" tab of my Xcode project had been switched back to "OFF". Switching this back fixed the issue.

**Comment by rishabh-altimetrik** [comment]
@sirhodes You sir have my thank. 
Can't believe something this simple was the issue I was struggling with since yesterday.

**Comment by sirhodes** [comment]
@rishabh-altimetrik glad that I could help! 👍

**Comment by Rui-Carvalho** [comment]
Oh my....after fighting with Xcode, App Dev Center (went through certificates and App IDs and the lots!!), ionic, this and that.... you sir, @sirhodes , pointed me in the right direction! 

It was the Push Notifications on Capabilities tab of Xcode that was triggering the dreaded "Push Plugin register failed" on Xdebug console for Phonegap push plugin registration step. Kudus to you @sirhodes 👍

**Comment by jimbobeen** [comment]
Same issue for me, thanks @sirhodes for the fix, saved me a few hours!

**Comment by abdulhafeez** [comment]
Thanks @sirhodes , I went through the same trouble until I saw this.

**Comment by samaparo** [comment]
Thanks, @sirhodes!

**Comment by kingkarki** [comment]
Thanks @sirhodes you saved many headaches.

**Comment by kbaggott** [comment]
Thanks @sirhodes

**Comment by manojrejinthala** [comment]
i am not able to get the device token from the ios or version 10.0 it returns the value of undefined please help me out to solve the problem and it is working fine in ios 9 and also ipad
