### ISSUE TITLE
onNotificationAPN not works on iOS9

### ISSUE THREAD

**Issue by oriolg23** [phonegap-build/PushPlugin#684]
Hello, I'm trying to use te PushPlugin for a iOS and Android (I haven't got any problem with Android push implementation), but when I want to implement the iOS code, it not work.

I can retrieve the token, but when I try to send a push notification example, the app does nothing.

I'm using the 2.5.0 version of the plugin, iOS 3.9.2 platform and Cordova 6.1.1.

I've tried the following codes:

function onNotificationAPN(e){....}

and

onNotificationAPN = function(e){...} 

But if i install the .ipa on an iPad running iOS 9.0 everything works except this. Even if the application opened or in the background.

Can anyone help me?

Thanks!

**Comment by macdonst** [comment]
@oriolg23 pretty sure this plugin was never tested with iOS9. We've moved all current development and support to https://github.com/phonegap/phonegap-plugin-push

**Comment by oriolg23** [comment]
Thanks! I'm trying to work with the new plugin!
