### ISSUE TITLE
What's the difference between this plugin and the push notification plugin in phonegap repo

### ISSUE THREAD

**Issue by greenlaw110** [phonegap-build/PushPlugin#689]
So there is another push notification plugin: https://github.com/phonegap/phonegap-plugin-push. And my testing tells me the [ng-cordova](https://github.com/driftyco/ng-cordova) works with the latter. I am curious what's the difference between the two plugins and why do you have `phonegap-build` while you already have `phonegap` organization.

**Comment by macdonst** [comment]
@greenlaw110 it's right in the README https://github.com/phonegap-build/PushPlugin#deprecated-cordova-push-notifications-plugin-for-android-ios-wp8-windows8-blackberry-10-and-amazon-fire-os
