### ISSUE TITLE
Push Plugin register failed - Confirmation popup is shown

### ISSUE THREAD

**Issue by txarlybarrera** [phonegap-build/PushPlugin#698]
Hi,

the registration event is not being triggered. In the xcode logs I see the error "Push Plugin register failed". Since I saw in this forum that it is usually due to the provisioning profiles, I generated them again and double / triple checked them. It should actually be working.

The APNS message "Do you allow this app to send you notifications..." is shown when the app is launched.

The most wierd thing is that the notifications were working perfectly (in dev and in prod) with other provisioning profiles.

Thanks and regards,
Carlos

**Comment by wildabeast** [comment]
This repo is deprecated, please go to [phonegap/phonegap-plugin-push](http://github.com/phonegap/phonegap-plugin-push).
