### ISSUE TITLE
App design issue

### ISSUE THREAD

**Issue by mbachaalani** [phonegap-build/PushPlugin#699]
Hello,

I had a version of cordova 4.0.2 and when I wanted to publish to the play store I could not because this version has security vulnerabilities. So I updated to version 5.2.2 but when I did that the app font and components zoomed in and the view was larger on each page (this happened for new devices like note5, htc, samsung S7, LG G2 but for older devices samsung S3 there is no problem). When I upgraded to 5.2.2, I was forced to update to the new push plugin. However when I found out it was causing the design issues I've removed it and the design was fixed on the devices. 
What is the source of the problem with the new push plugin with the rendering of new android devices?

btw: I am using media queries to render elements specifically for each group of devices.
Please I need help with this issue.
Thank you.

**Comment by wildabeast** [comment]
You should post this issue to the [new push plugin repo](http://github.com/phonegap/phonegap-plugin-push), this one is no longer active and your question won't get visibility.
