### ISSUE TITLE
build phonegap on cli-6.3.0

### ISSUE THREAD

**Issue by MahmoudFawzy** [phonegap-build/PushPlugin#701]
*\* BUILD FAILED **

The following build commands failed:
    CompileC build/Salonak.build/Release-iphoneos/Salonak.build/Objects-normal/armv7/PushPlugin.o Salonak/Plugins/com.phonegap.plugins.PushPlugin/PushPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by dturakhia** [comment]
Anyway that you were able to fix this issue?

**Comment by MahmoudFawzy** [comment]
I change this plugin with this push plugin https://github.com/phonegap/phonegap-plugin-push
