### ISSUE TITLE
Error calling method on NPObject. at file:///android_asset/www/cordova.js:929

### ISSUE THREAD

**Issue by kuczek** [phonegap-build/PushPlugin#92]
Cordova 3.1, it's caused by sendJavascript function from gWebView.
Whatever I put in gWebView.sendJavascript i tried 'javascript: alert("x")', and 'alert("x")' thre result is always the same.

**Comment by Khaleela-visolve** [comment]
Hi,

I am using Cordova 5.1.1, i found the same issue ....

**Comment by printoa** [comment]
I am using Cordova 5.1.1, i found the same issue ....And my error is,
error uncaught Error: Method not found in file://android_asset/www/cordova.js at line 943.

I updated the cordova-lib and updated android platform and also the plugins...
